Update loading.py
UnicodeDecodeError: 'gbk' codec can't decode byte 0xaa in position 55: illegal multibyte sequence #17995
The default encoding mode of the Windows system is 'gbk', and you need to specify the decoding mode as 'utf-8'.
langchain_core->prompts->loading.py->load_template line46
with open(template_path) as f: -> with open(template_path, encoding="utf-8") as f: